"use client"

import React from "react"
import styles from "@/app/css/styles.module.css"
import { Grid, Header } from "semantic-ui-react"
import Head from "next/head"

export default function Success() {
  return (
    <>
      <Head>
        <title>Form Submitted</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid centered>
        <Grid.Row>
          <Grid.Column mobile={12} tablet={10} computer={8} textAlign="center">
            <Header as="h1">Form successfully submitted!</Header>
          </Grid.Column>
        </Grid.Row>
        <Grid.Row>
          <Grid.Column mobile={12} tablet={10} computer={8} textAlign="center">
            <p>
              Thank you for submitting the form! I will get back with you as
              soon as possible!
            </p>
            <p>
              Note: this form does not actually submit anything at the moment.
              If you would like to get in contact with me, please send an email{" "}
              <a href="mailto:mychalwood@gmail.com">mychalwood@gmail.com</a>.
              Thank you! 😁
            </p>
          </Grid.Column>
        </Grid.Row>
      </Grid>
    </>
  )
}
