import { Inter } from "next/font/google";
import "./css/globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mychal Wood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="pagescroll">
          <div className="app">{children}</div>
        </div>
      </body>
    </html>
  );
}
